language: python
python:
  - "2.7"

branch:
    only:
        - master
# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install -e .
# command to run tests
script:
    - cd flask_report/test/
    - python splinter_tests.py
notifications:
    email:
      recipients:
        - abc549825@163.com
        - xiechao06@gmail.com
