columns: [0, 2, 3, 4, 5]
create_time: '2013-07-15 20:20:35'
creator: 'xiechao'
data_set_id: 1
description: ''
filters:
  Group.name: [{operator: ne, value: 魏}, {operator: ne, value: 蜀}]
name: 三国时期吴国人物报告
